### ISSUE TITLE
Chapter2 3-cnn.py reshaping T.matrix()

### ISSUE THREAD

**Issue by atulshanbhag** [PacktPublishing/Deep-Learning-with-Theano#2]
x = T.matrix('x')
    layer0_input = x.reshape((batch_size, 1, 28, 28))

Aren't these 2 lines contradictory? How can T.matrix() be reshaped to 4 dimensions?

**Comment by christopher5106** [comment]
The purpose of reshape function is to change the number of dimension. :)
As soon as the size (number of elements) remains the same.
