### ISSUE TITLE
where is the code for chapters 07, 08, 09?

### ISSUE THREAD

**Issue by dumpinfo** [PacktPublishing/Deep-Learning-with-Theano#4]
For chapters 07, 08, 09, code will be published soon. Use the code from the chapter in the mean time.
two years passed,where is the code????

**Comment by shubham763** [comment]
Hi @dumpinfo 
For chapter 01, 07, 08, 09, 10 and 12 use the code from the chapter. There are no additional code files for chapter 07 and 08.
